//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonuri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonuri()
        {
            this.Produs_Bon = new HashSet<Produs_Bon>();
        }
    
        public int id_bon { get; set; }
        public System.DateTime data_eliberare { get; set; }
        public int id_casier { get; set; }
        public double total { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produs_Bon> Produs_Bon { get; set; }
    }
}
