//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produse()
        {
            this.Produs_Bon = new HashSet<Produs_Bon>();
            this.Stocuri = new HashSet<Stocuri>();
        }
    
        public int id_produs { get; set; }
        public string nume { get; set; }
        public string cod_bare { get; set; }
        public string categorie { get; set; }
        public int id_producator { get; set; }
        public bool is_active { get; set; }
    
        public virtual Producatori Producatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produs_Bon> Produs_Bon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stocuri> Stocuri { get; set; }
    }
}
